# Generated by Django 5.1.4 on 2025-06-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='bookname',
        ),
    ]
