# Generated by Django 5.1.4 on 2025-06-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='name',
            new_name='membername',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='membername',
        ),
    ]
